### PR TITLE
Updated for Laravel 7

### PR DESCRIPTION
**Pull request by kalizi**
Hi, I updated the package for Laravel 7.

- Exception handler Exception was moved to Throwable, PHP version must be increased due to this change. I also changed all methods name changing "exception" to "throwable".
- During tests I also had to update ramsey/uuid to version ^4, I checked upgrade guide and the version has no major upgrades but return types, so I just moved the string cast to the toString method call. 
- In order to work correctly, the [antonioribeiro/laravel4-datatables-package](antonioribeiro/laravel4-datatables-package) must be updated, there's already a PR: https://github.com/antonioribeiro/laravel4-datatables-package/pull/4

Thanks in advance.

### CODE REVIEW

**Comment by quanta-2019** [comment]
@kalizi good job on submitting this so soon. Is there a TL;DR method of installing your fork? The readme just has us install antonioribeiro's which is currently incompatible.

**Comment by kalizi** [comment]
@quanta-2019 sure, composer allow you to install repositories from a local folder, here's the official documentation https://getcomposer.org/doc/05-repositories.md#path
You just have to clone the repository in a local folder and edit your composer.json pointing to that.
If you're getting troubles with repository name, open the composer.json of the cloned repository and change the name to something like "tracker2" or something similar.

**Comment by antonioribeiro** [comment]
@kalizi ,

Why force PHP >= 7?

What happens with with lower versions of PHP and Laravel relying on it?

As soon as this is merged I'm sure we will have a lot of complaints, OSS is hard.

**Comment by kalizi** [comment]
Because Throwable is available just on php7 https://www.php.net/manual/en/class.throwable.php

**Comment by kalizi** [comment]
@antonioribeiro the only way to keep backward compatibility in the same version, is to keep two ExceptionHandler, one with Throwable and one with Exception and change the way Exception Handler is registered ([`ServiceProvider:394`](https://github.com/antonioribeiro/tracker/blob/76e8e7fa058c6b1c15fea4b2ffa5169ae087d6f7/src/Vendor/Laravel/ServiceProvider.php#L394)) by switching it basic on PHP version, but I think it's not a clean solution. Laravel has updated PHP Version to 7 since 5.5 (https://github.com/laravel/laravel/blob/5.5/composer.json), and by default `Exception extends Throwable` (https://www.php.net/manual/en/class.exception.php) so this shouldn't be a problem.

**Comment by antonioribeiro** [comment]
I just merged it and tagged a new major version, because this is a huge breaking change for a lot of people, but I also believe we have to move forward. Thank you @kalizi.

**Comment by sudinem** [comment]
Is this package not compatible for Laravel 7 ?

**Pull request merged**
