### PR TITLE
fix `Illegal offset type in isset or empty` and `Undefined method Tracker::getSessionData()`

### PR DESCRIPTION
**Pull request by marlocorridor**
for issue #188 and #218

### CODE REVIEW

**Comment by marlocorridor** [comment]
I do not understand why this error occur

`Argument 1 passed to PragmaRX\Tracker\Data\RepositoryManager::__construct() must be an instance of PragmaRX\Tracker\Data\GeoIP, instance of PragmaRX\Support\GeoIp\GeoIp given, called in C:\Users\RichtelDonne\Desktop\mapi\vendor\pragmarx\tracker\src\Vendor\Laravel\ServiceProvider.php on line 322`

please help. :)

**Comment by fntneves** [comment]
@marlocorridor Please, go to file src/Data/Repository.php and add this to the top so it will get the type it wants:

```
use PragmaRX\Support\GeoIp\GeoIp;
```

**Comment by marlocorridor** [comment]
Thanks a lot @fntneves . :)

**Comment by KeitelDOG** [comment]
Why hasn't this branch been merged yet? I got the "Call to undefined method PragmaRX\Tracker\Tracker::getSessionData()" when migrating from Laravel 4.2 to 5.0 .
Please @antonioribeiro or other Admin could you add this fix? Cause I really need this error fixed before I update my Staging Server.

**Comment by fntneves** [comment]
@marlocorridor You're welcome! :D

Would you please also commit that fix, if it is not already available?

**Comment by marlocorridor** [comment]
@fntneves included on my new commit. :)

**Comment by KeitelDOG** [comment]
@fntneves Could you please merge changes. I'm gonna upgrade from Laravel 4.2 to 5.0 on my Staging Server on Friday. And may be to Production the same day or on Saturday.

**Comment by fntneves** [comment]
@KeitelDOG I am not an admin of this repository. I would like to merge changes, actually.

\cc @antonioribeiro

**Comment by KeitelDOG** [comment]
@fntneves sorry I didn't know. I was just about to connect to my Staging server to upgrade to Laravel 5.0, and I check if it was merged. So I have no choice to do some code hacking on the files till then. Thanks.

**Comment by antonioribeiro** [comment]
Sorry for the delay, merged.

**Pull request merged**
